dependencies: \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Modules/RCTUIManager.m \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Modules/RCTUIManager.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTBridge.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTBridgeDelegate.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTJavaScriptLoader.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTDefines.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTBridgeModule.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTFrameUpdate.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTInvalidating.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTRootView.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Views/RCTViewManager.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTConvert.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Views/RCTAnimationType.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Views/RCTBorderStyle.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTLog.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTAssert.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTUtils.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Views/RCTPointerEvents.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Views/RCTTextDecorationLineType.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/yoga/Yoga.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/yoga/YGEnums.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/yoga/YGMacros.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/yoga/YGValue.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTEventDispatcher.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Views/UIView+React.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Views/RCTComponent.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Modules/RCTAccessibilityManager.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTBridge+Private.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Views/RCTComponentData.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Modules/RCTLayoutAnimation.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Modules/RCTLayoutAnimationGroup.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTModuleData.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTModuleMethod.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTBridgeMethod.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTNullability.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Profiler/RCTProfile.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTRootContentView.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Views/RCTView.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Views/RCTRootShadowView.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Views/RCTShadowView.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Views/RCTLayout.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/RCTRootViewInternal.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Views/ScrollView/RCTScrollableProtocol.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Views/RCTShadowView+Internal.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/Surface/RCTSurfaceRootShadowView.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/Surface/RCTSurfaceRootShadowViewDelegate.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Base/Surface/RCTSurfaceRootView.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Modules/RCTUIManagerObserverCoordinator.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/React/Modules/RCTUIManagerUtils.h
