dependencies: \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/Libraries/Network/RCTNetworking.mm \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTAssert.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTDefines.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTAnimationType.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTBorderStyle.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTLog.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTUtils.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTPointerEvents.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTTextDecorationLineType.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/yoga/Yoga.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/yoga/YGEnums.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/yoga/YGMacros.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/yoga/YGValue.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTEventDispatcher.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTBridge.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTBridgeDelegate.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTJavaScriptLoader.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTBridgeModule.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTFrameUpdate.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTInvalidating.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTNetworkTask.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTURLRequestDelegate.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTURLRequestHandler.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTNetworking.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTEventEmitter.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native/Libraries/Network/RCTHTTPRequestHandler.h
