dependencies: \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native-gesture-handler/ios/RNGestureHandlerModule.m \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native-gesture-handler/ios/RNGestureHandlerModule.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTEventEmitter.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTBridge.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTBridgeDelegate.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTJavaScriptLoader.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTDefines.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTBridgeModule.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTFrameUpdate.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTInvalidating.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTUIManager.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTRootView.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTViewManager.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTAnimationType.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTBorderStyle.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTLog.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTAssert.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTUtils.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTPointerEvents.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTTextDecorationLineType.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/yoga/Yoga.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/yoga/YGEnums.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/yoga/YGMacros.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/yoga/YGValue.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTEventDispatcher.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/UIView+React.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTComponent.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTUIManagerUtils.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/ios/build/QuanLyXe/Build/Products/Debug-iphonesimulator/include/React/RCTUIManagerObserverCoordinator.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native-gesture-handler/ios/RNGestureHandlerState.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native-gesture-handler/ios/RNGestureHandlerDirection.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native-gesture-handler/ios/RNGestureHandler.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native-gesture-handler/ios/RNGestureHandlerEvents.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native-gesture-handler/ios/RNGestureHandlerManager.h \
  /Users/cv10001m/Desktop/thienle/QuanLyXe/node_modules/react-native-gesture-handler/ios/RNGestureHandlerButton.h
